
oauth2:
  instance:
    github:
      authServerUrl: https://github.com/login/oauth/authorize
      accessTokenUrl: https://github.com/login/oauth/access_token
      fetchInfoUrl: https://api.github.com/user
      clientId: Ov23linP6FicPDQccva1
      clientSecret: 583c8ff3338ede3d3eb5c7fdf6849f81dc63350c
      callBackUrl: http://localhost:7529/api/user/oauth2/github/callback